import express from 'express';
import persistenceRouter from './server/persistence';
import { buildPublicRoutingInstruction, classifyPublicRequest } from './server/publicIntake';
import { buildGlobalTaskReview } from './server/globalTaskReview';
import { buildDailyReview, buildTomorrowPlan } from './server/dailyReview';
import { extractMentalTasks, formatMentalTaskSummary } from './server/mentalTaskIntake';

const originalUse=express.application.use;let useCount=0;let mounted=false;let corsMounted=false;
const DOMAIN_LABELS:Record<string,string>={work:'工作',study:'課業／研究',personal:'個人規劃',global:'全域任務管理'};
express.application.use=function patchedUse(...args:any[]){useCount+=1;if(!corsMounted){corsMounted=true;originalUse.call(this,(req:any,res:any,next:any)=>{const origin=req.headers.origin as string|undefined;const allowedOrigins=new Set(['https://312460040.github.io','http://localhost:5173','http://127.0.0.1:5173',process.env.FRONTEND_ORIGIN].filter(Boolean) as string[]);if(origin&&allowedOrigins.has(origin)){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');}res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,PATCH,DELETE,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, X-Owner-Id, Authorization');if(req.method==='OPTIONS')return res.status(204).end();next();});}if(!mounted&&useCount>=2){mounted=true;originalUse.call(this,'/api/persistence',persistenceRouter);}return originalUse.apply(this,args as any);};
const originalPost=express.application.post;
express.application.post=function patchedPost(path:any,...handlers:any[]){if(path==='/api/agent/chat'&&handlers.length){const wrappedHandlers=handlers.map((handler:any)=>{if(typeof handler!=='function')return handler;return async function publicIntakeHandler(this:any,req:any,res:any,next:any){const context=req.body?.context;const room=context?.chatRoom;const isPublicRoom=room?.id==='room-public'||room?.chatRoomId==='room-public'||context?.chatRoomId==='room-public'||context?.currentContext?.workspaceId==='public';if(!isPublicRoom)return handler.call(this,req,res,next);const message=String(req.body?.message||'');const result=await classifyPublicRequest(message,context?.workProjects||[]);const routingInstruction=buildPublicRoutingInstruction(result);const mentalTasks=result.mode==='normal'?await extractMentalTasks(message):[];const mentalTaskSummary=formatMentalTaskSummary(mentalTasks);req.body.context={...context,publicIntake:{...result,routingInstruction,mentalTasks},currentContext:{workspaceId:result.category==='work'?'work':result.category==='study'?'study':result.category==='global'?'global':'personal',projectId:result.category==='work'?result.projectId:null}};const originalJson=res.json.bind(res);res.json=(payload:any)=>{const routedPayload={...payload,publicIntake:req.body.context.publicIntake};if(typeof routedPayload.finalSynthesisMarkdown==='string'){const label=DOMAIN_LABELS[result.category];const projectNote=result.projectId?`\n- 專案：已安全匹配既有專案（${result.projectId}）`:result.category==='work'?'\n- 專案：尚未指定，Manager 不會自行猜測':'';routedPayload.finalSynthesisMarkdown=`### 🧭 Manager 分流\n- 類別：**${label}**\n- 模式：**${result.mode}**\n- 信心：**${result.confidence}**\n- 判斷方式：**${result.method==='ai'?'AI 語意理解':'規則備援'}**\n- 判斷：${result.reason}${projectNote}\n\n${mentalTaskSummary?`${mentalTaskSummary}\n\n`:''}`+routedPayload.finalSynthesisMarkdown;}return originalJson(routedPayload);};
if(result.category==='global'){const report=result.mode==='daily_review'?buildDailyReview(context):result.mode==='tomorrow_plan'?buildTomorrowPlan(context):buildGlobalTaskReview(context);const modeLabel=result.mode==='daily_review'?'每日覆盤':result.mode==='tomorrow_plan'?'隔日規劃':'全域任務唯讀盤點';return res.json({intentType:result.mode==='daily_review'?'DAILY_REVIEW':result.mode==='tomorrow_plan'?'TOMORROW_PLAN':'GLOBAL_TASK_REVIEW',delegatedAgents:['work','study'],activityLogs:[{id:`act-manager-${Date.now()}`,timestamp:new Date().toISOString(),stepIndex:1,fromAgent:'manager',action:modeLabel,summary:'跨工作與課業整理 User Tasks',detail:'Manager-level 唯讀分析；等待 Owner 審核後才進入安排。',status:'completed',durationMs:0}],workOutput:report,studyOutput:'',finalSynthesisMarkdown:report,proposedTimeBlocks:[],createdTaskPayload:null,durationTotalMs:0,publicIntake:req.body.context.publicIntake});}
try{return await handler.call(this,req,res,next);}catch(error){return next(error);}});return originalPost.call(this,path,...wrappedHandlers);}return originalPost.call(this,path,...handlers);};
import('./server.ts').catch(error=>{console.error('Failed to start Personal AI Team server:',error);process.exitCode=1;});
