import { randomUUID } from 'node:crypto';

type Row = Record<string, any>;
function env(name: string) { const value = process.env[name]; if (!value) throw new Error(`${name} is not configured`); return value.replace(/\/$/, ''); }
async function supabase(path: string, init: RequestInit = {}) { const key = env('SUPABASE_SERVICE_ROLE_KEY'); const response = await fetch(`${env('SUPABASE_URL')}/rest/v1/${path}`, { ...init, headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json', ...(init.headers || {}) } }); const text = await response.text(); if (!response.ok) throw new Error(`Supabase ${response.status}: ${text.slice(0, 500)}`); return text ? JSON.parse(text) : []; }
function q(value: string) { return encodeURIComponent(value); }
export type PersonalToolContext = { userId: string; writeAuthorized: boolean };
export type PersonalToolResult = { ok: boolean; tool: string; data?: any; error?: string };
const dateToday = () => new Date().toISOString().slice(0, 10);
async function habit(ctx: PersonalToolContext, id: string) { const rows = await supabase(`personal_habits?user_id=eq.${q(ctx.userId)}&id=eq.${q(id)}&select=*&limit=1`); return Array.isArray(rows) ? rows[0] : null; }

export async function getHabits(ctx: PersonalToolContext, args: any = {}): Promise<PersonalToolResult> { const active = typeof args.active === 'boolean' ? `&active=eq.${args.active}` : ''; const rows = await supabase(`personal_habits?user_id=eq.${q(ctx.userId)}${active}&select=*&order=active.desc,created_at.desc&limit=${Math.min(Math.max(Number(args.limit)||50,1),100)}`); return { ok:true, tool:'get_habits', data:Array.isArray(rows)?rows:[] }; }
export async function createHabit(ctx: PersonalToolContext, args: any = {}): Promise<PersonalToolResult> { if (!ctx.writeAuthorized) return {ok:false,tool:'create_habit',error:'WRITE_NOT_AUTHORIZED'}; const name=String(args.name||'').trim().slice(0,120); if(!name)return {ok:false,tool:'create_habit',error:'NAME_REQUIRED'}; const frequency=['daily','weekly','custom'].includes(args.frequency)?args.frequency:'daily'; const targetDays=Array.isArray(args.targetDays)?args.targetDays.slice(0,7):[]; const reminderTime=typeof args.reminderTime==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(args.reminderTime)?args.reminderTime:null; const now=new Date().toISOString(); const row={id:String(args.id||randomUUID()),user_id:ctx.userId,name,description:typeof args.description==='string'?args.description.slice(0,1000):null,frequency,target_days:targetDays,reminder_time:reminderTime,active:true,current_streak:0,best_streak:0,source:'agent',created_at:now,updated_at:now}; const created=await supabase('personal_habits',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}); return {ok:true,tool:'create_habit',data:Array.isArray(created)?created[0]:created}; }
export async function updateHabit(ctx: PersonalToolContext,args:any={}):Promise<PersonalToolResult>{if(!ctx.writeAuthorized)return{ok:false,tool:'update_habit',error:'WRITE_NOT_AUTHORIZED'};const id=String(args.habitId||'');const existing=await habit(ctx,id);if(!existing)return{ok:false,tool:'update_habit',error:'HABIT_NOT_FOUND_OR_NOT_OWNED'};const updates:any={updated_at:new Date().toISOString()};if(typeof args.name==='string'&&args.name.trim())updates.name=args.name.trim().slice(0,120);if(typeof args.description==='string')updates.description=args.description.slice(0,1000);if(['daily','weekly','custom'].includes(args.frequency))updates.frequency=args.frequency;if(Array.isArray(args.targetDays))updates.target_days=args.targetDays.slice(0,7);if(typeof args.active==='boolean')updates.active=args.active;if(typeof args.reminderTime==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(args.reminderTime))updates.reminder_time=args.reminderTime;if(!Object.keys(updates).some(k=>k!=='updated_at'))return{ok:false,tool:'update_habit',error:'NO_VALID_UPDATES'};const rows=await supabase(`personal_habits?user_id=eq.${q(ctx.userId)}&id=eq.${q(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(updates)});return{ok:true,tool:'update_habit',data:Array.isArray(rows)?rows[0]:rows};}
export async function checkInHabit(ctx:PersonalToolContext,args:any={}):Promise<PersonalToolResult>{if(!ctx.writeAuthorized)return{ok:false,tool:'checkin_habit',error:'WRITE_NOT_AUTHORIZED'};const id=String(args.habitId||'');const existing=await habit(ctx,id);if(!existing)return{ok:false,tool:'checkin_habit',error:'HABIT_NOT_FOUND_OR_NOT_OWNED'};const checkinDate=typeof args.date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(args.date)?args.date:dateToday();const previous=await supabase(`habit_checkins?user_id=eq.${q(ctx.userId)}&habit_id=eq.${q(id)}&checkin_date=eq.${q(checkinDate)}&select=id&limit=1`);if(Array.isArray(previous)&&previous[0])return{ok:false,tool:'checkin_habit',error:'ALREADY_CHECKED_IN'};const inserted=await supabase('habit_checkins',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({id:randomUUID(),habit_id:id,user_id:ctx.userId,checkin_date:checkinDate,note:typeof args.note==='string'?args.note.slice(0,500):null})});const streakRows=await supabase(`habit_checkins?user_id=eq.${q(ctx.userId)}&habit_id=eq.${q(id)}&select=checkin_date&order=checkin_date.desc&limit=366`);const dates=(Array.isArray(streakRows)?streakRows:[]).map((r:Row)=>String(r.checkin_date));let streak=0;let cursor=new Date(`${checkinDate}T00:00:00Z`);for(const value of dates){const expected=cursor.toISOString().slice(0,10);if(value!==expected)break;streak++;cursor.setUTCDate(cursor.getUTCDate()-1);}const best=Math.max(Number(existing.best_streak||0),streak);const updated=await supabase(`personal_habits?user_id=eq.${q(ctx.userId)}&id=eq.${q(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({current_streak:streak,best_streak:best,last_completed_on:checkinDate,updated_at:new Date().toISOString()})});return{ok:true,tool:'checkin_habit',data:{habit:Array.isArray(updated)?updated[0]:updated,checkin:Array.isArray(inserted)?inserted[0]:inserted,streak,bestStreak:best}};}
export async function getMemos(ctx:PersonalToolContext,args:any={}):Promise<PersonalToolResult>{const archived=typeof args.archived==='boolean'?`&archived=eq.${args.archived}`:'&archived=eq.false';const rows=await supabase(`personal_memos?user_id=eq.${q(ctx.userId)}${archived}&select=*&order=pinned.desc,updated_at.desc&limit=${Math.min(Math.max(Number(args.limit)||50,1),100)}`);return{ok:true,tool:'get_memos',data:Array.isArray(rows)?rows:[]};}
export async function createMemo(ctx:PersonalToolContext,args:any={}):Promise<PersonalToolResult>{if(!ctx.writeAuthorized)return{ok:false,tool:'create_memo',error:'WRITE_NOT_AUTHORIZED'};const content=String(args.content||'').trim().slice(0,10000);if(!content)return{ok:false,tool:'create_memo',error:'CONTENT_REQUIRED'};const now=new Date().toISOString();const created=await supabase('personal_memos',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({id:randomUUID(),user_id:ctx.userId,title:String(args.title||'').trim().slice(0,200),content,pinned:Boolean(args.pinned),archived:false,source:'agent',created_at:now,updated_at:now})});return{ok:true,tool:'create_memo',data:Array.isArray(created)?created[0]:created};}
export async function updateMemo(ctx:PersonalToolContext,args:any={}):Promise<PersonalToolResult>{if(!ctx.writeAuthorized)return{ok:false,tool:'update_memo',error:'WRITE_NOT_AUTHORIZED'};const id=String(args.memoId||'');const rows=await supabase(`personal_memos?user_id=eq.${q(ctx.userId)}&id=eq.${q(id)}&select=*&limit=1`);if(!Array.isArray(rows)||!rows[0])return{ok:false,tool:'update_memo',error:'MEMO_NOT_FOUND_OR_NOT_OWNED'};const updates:any={updated_at:new Date().toISOString()};if(typeof args.title==='string')updates.title=args.title.trim().slice(0,200);if(typeof args.content==='string'&&args.content.trim())updates.content=args.content.trim().slice(0,10000);if(typeof args.pinned==='boolean')updates.pinned=args.pinned;if(typeof args.archived==='boolean')updates.archived=args.archived;const updated=await supabase(`personal_memos?user_id=eq.${q(ctx.userId)}&id=eq.${q(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(updates)});return{ok:true,tool:'update_memo',data:Array.isArray(updated)?updated[0]:updated};}
export async function executePersonalTool(name:string,ctx:PersonalToolContext,args:any):Promise<PersonalToolResult>{try{switch(name){case'get_habits':return await getHabits(ctx,args);case'create_habit':return await createHabit(ctx,args);case'update_habit':return await updateHabit(ctx,args);case'checkin_habit':return await checkInHabit(ctx,args);case'get_memos':return await getMemos(ctx,args);case'create_memo':return await createMemo(ctx,args);case'update_memo':return await updateMemo(ctx,args);default:return{ok:false,tool:name,error:'UNKNOWN_PERSONAL_TOOL'}}}catch(error){return{ok:false,tool:name,error:error instanceof Error?error.message:String(error)}}}
export const PERSONAL_TOOL_DECLARATIONS=[
{name:'get_habits',description:'查詢 Owner 的日常習慣與目前連續打卡狀態。',parameters:{type:'object',properties:{active:{type:'boolean'},limit:{type:'integer'}}}},
{name:'create_habit',description:'建立 Owner 的日常習慣。',parameters:{type:'object',required:['name'],properties:{name:{type:'string'},description:{type:'string'},frequency:{type:'string',enum:['daily','weekly','custom']},targetDays:{type:'array',items:{type:'integer'}},reminderTime:{type:'string'}}}},
{name:'update_habit',description:'修改 Owner 已存在的習慣。',parameters:{type:'object',required:['habitId'],properties:{habitId:{type:'string'},name:{type:'string'},description:{type:'string'},frequency:{type:'string',enum:['daily','weekly','custom']},targetDays:{type:'array',items:{type:'integer'}},reminderTime:{type:'string'},active:{type:'boolean'}}}},
{name:'checkin_habit',description:'替 Owner 的習慣完成一次打卡；同一天同一習慣不可重複打卡。',parameters:{type:'object',required:['habitId'],properties:{habitId:{type:'string'},date:{type:'string'},note:{type:'string'}}}},
{name:'get_memos',description:'查詢 Owner 的個人備忘錄。',parameters:{type:'object',properties:{archived:{type:'boolean'},limit:{type:'integer'}}}},
{name:'create_memo',description:'建立 Owner 的個人備忘錄。',parameters:{type:'object',required:['content'],properties:{title:{type:'string'},content:{type:'string'},pinned:{type:'boolean'}}}},
{name:'update_memo',description:'修改、釘選或封存 Owner 已存在的備忘錄。',parameters:{type:'object',required:['memoId'],properties:{memoId:{type:'string'},title:{type:'string'},content:{type:'string'},pinned:{type:'boolean'},archived:{type:'boolean'}}}},
] as const;
