import React,{useEffect,useMemo,useState} from 'react';
import {CalendarDays,ChevronLeft,ChevronRight,RefreshCw} from 'lucide-react';

type E={googleEventId?:string;title:string;startAt:string;endAt:string};
const weekStart=(x:Date)=>{const d=new Date(x);d.setDate(d.getDate()-d.getDay());d.setHours(0,0,0,0);return d};
const addDays=(x:Date,n:number)=>{const d=new Date(x);d.setDate(d.getDate()+n);return d};
const CalendarView:React.FC=()=>{const [anchor,setAnchor]=useState(new Date());const [events,setEvents]=useState<E[]>([]);const [connected,setConnected]=useState(false);const [email,setEmail]=useState('');const [loading,setLoading]=useState(false);const start=useMemo(()=>weekStart(anchor),[anchor]);const days=useMemo(()=>Array.from({length:7},(_,i)=>addDays(start,i)),[start]);
const load=async()=>{setLoading(true);try{const s=await fetch('/api/calendar/status',{headers:{'X-Owner-Id':'personal-owner'}}).then(r=>r.json());setConnected(!!s.connected);setEmail(s.email||'');if(!s.connected){setEvents([]);return}const data=await fetch(`/api/calendar/events?from=${encodeURIComponent(start.toISOString())}&to=${encodeURIComponent(addDays(start,7).toISOString())}`,{headers:{'X-Owner-Id':'personal-owner'}}).then(r=>r.json());setEvents(Array.isArray(data.events)?data.events:[])}finally{setLoading(false)}};
useEffect(()=>{void load()},[start.toISOString()]);
const connect=()=>{window.location.href='/api/calendar/auth'};
return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-900 text-white"><CalendarDays className="h-5 w-5"/></div><div><p className="text-sm text-slate-500">Calendar Integration</p><h2 className="text-xl font-bold">📅 我的行事曆</h2><p className="text-xs text-slate-500">{connected?`Google Calendar：${email||'已連接'}`:'尚未連接 Google Calendar'}</p></div></div><div className="flex gap-2"><button onClick={()=>setAnchor(addDays(anchor,-7))} className="rounded-xl border p-2"><ChevronLeft className="h-4 w-4"/></button><button onClick={()=>setAnchor(new Date())} className="rounded-xl border px-3 py-2 text-xs">今天</button><button onClick={()=>setAnchor(addDays(anchor,7))} className="rounded-xl border p-2"><ChevronRight className="h-4 w-4"/></button><button onClick={()=>void load()} className="rounded-xl border px-3 py-2 text-xs"><RefreshCw className={`mr-1 inline h-3.5 w-3.5 ${loading?'animate-spin':''}`}/>同步</button>{!connected&&<button onClick={connect} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-semibold text-white">連接 Google Calendar</button>}</div></div>{connected?<div className="mt-5 grid grid-cols-1 gap-3 md:grid-cols-7">{days.map(d=>{const es=events.filter(e=>{const x=new Date(e.startAt);return x.toDateString()===d.toDateString()});return <div key={d.toISOString()} className="min-h-40 rounded-xl border border-slate-200 p-3"><p className="text-xs text-slate-500">{d.toLocaleDateString('zh-TW',{weekday:'short'})}</p><p className="text-lg font-bold">{d.getDate()}</p><div className="mt-2 space-y-2">{es.map(e=><div key={e.googleEventId} className="rounded-lg bg-slate-100 p-2"><p className="text-[11px] font-mono text-slate-500">{new Date(e.startAt).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false})}–{new Date(e.endAt).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false})}</p><p className="text-xs font-semibold">{e.title}</p></div>)}</div></div>})}</div>:<div className="mt-5 rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">完成 Google OAuth 後，這裡會顯示你的行程；Manager 也會把 Calendar 當成排程限制。</div>}</section>};
export default CalendarView;
