import React,{useEffect,useRef}from'react';
import{useAppData}from'../context/AppDataContext';
import type{WorkProject,WorkTask,StudySubject,StudyTask,TodayTimeBlock}from'../types';
import{apiUrl}from'../services/apiBase';
import{classifyWorkTaskCategory}from'../data/workTaxonomy';
import{LI_ROOT_TITLE,LI_SITES,inferLiSiteFromTask}from'../data/workHierarchy';
const OWNER_ID='personal-owner',SYNC_DELAY=900;const PARENT_ID='proj-client-li-medical';
const SITE_IDS:Record<string,string>={'立博':'proj-site-libor','新仁':'proj-site-xinren','世博':'proj-site-shibo','泰安':'proj-site-taian','板國':'proj-site-banguo','博淘':'proj-site-botao'};
const CLIENT_IDS:Record<string,string>={[LI_ROOT_TITLE]:PARENT_ID,'綜合醫院':'proj-client-general-hospital','旅遊業的客戶':'proj-client-travel'};
type Snapshot={projects:any[];tasks:any[];studySubjects:any[];todayBlocks:any[]};
function fromProject(row:any):WorkProject{return{id:String(row.id),workspaceId:row.workspace_id||'work',title:row.title||'未命名專案',category:row.category||'work',progress:Number(row.progress||0),priority:row.priority==='high'||row.priority==='low'?row.priority:'medium',deadline:row.deadline||'',description:row.description||'',status:row.status||'planning',owner:row.owner||undefined,tags:Array.isArray(row.tags)?row.tags:[],source:'user',createdBy:'user',parentProjectId:row.parent_project_id?String(row.parent_project_id):undefined,projectType:row.project_type||undefined};}
function fromWorkTask(row:any):WorkTask{return{id:String(row.id),workspaceId:row.workspace_id||'work',projectId:row.project_id||'',projectName:row.project_name||'',title:row.title||'未命名任務',priority:row.priority==='high'||row.priority==='low'?row.priority:'medium',status:row.status||'todo',startDate:row.start_at?String(row.start_at).slice(0,10):undefined,deadline:row.deadline||'',estimatedHours:Number(row.estimated_hours||0),assignee:row.assignee||undefined,notes:row.notes||undefined,tags:Array.isArray(row.tags)?row.tags:[],isUrgent:Boolean(row.is_urgent),source:'user',createdBy:'user'};}
function fromStudyTask(row:any,subjects:StudySubject[]):StudyTask{const subject=subjects.find(s=>s.id===row.subject_id);return{id:String(row.id),subjectId:row.subject_id||'',subjectName:subject?.name||row.subject_name||'',title:row.title||'未命名課業',type:'study_task',deadline:row.deadline||'',progress:Number(row.progress||0),estimatedHours:Number(row.estimated_hours||0),priority:row.priority==='high'||row.priority==='low'?row.priority:'medium',status:row.status||'todo',notes:row.notes||undefined,source:'user',createdBy:'user'};}
function fromSubject(row:any):StudySubject{return{id:String(row.id),name:row.name||'未命名科目',code:row.code||'',credits:Number(row.credits||0),progress:Number(row.progress||0),nextExamDate:row.next_exam_date||undefined,supervisorTone:row.supervisor_tone||undefined,teacherOrNotes:row.teacher_or_notes||undefined,status:row.status||'in_progress',focusTopics:Array.isArray(row.focus_topics)?row.focus_topics:[],source:'user'};}
function fromBlock(row:any):TodayTimeBlock{return{id:String(row.id),timeRange:row.time_range||'',type:row.type||'buffer',title:row.title||'時間區塊',agentOwner:row.agent_owner||'manager',targetDurationMin:Number(row.target_duration_min||0),completed:Boolean(row.completed),notes:row.notes||undefined,priority:row.priority==='high'||row.priority==='low'?row.priority:'medium',visualPriority:row.visual_priority||undefined,recurring:Boolean(row.recurring),source:'user',createdBy:'user'};}
const userOnly=<T extends{source?:string}>(items:T[])=>items.filter(item=>item.source==='user');
function canonicalId(p:any){const title=String(p.title||'').trim();if(CLIENT_IDS[title])return CLIENT_IDS[title];if(SITE_IDS[title])return SITE_IDS[title];return String(p.id||'');}
function canonicalProjects(items:any[]){const map=new Map<string,any>();for(const item of items){const id=canonicalId(item);if(!id)continue;const next={...item,id};const old=map.get(id);if(!old||((item.source==='user'?1:0)+(item.description?1:0))>((old.source==='user'?1:0)+(old.description?1:0)))map.set(id,next);}
 const out=Array.from(map.values());for(const p of out){const title=String(p.title||'').trim();if(title===LI_ROOT_TITLE||title==='綜合醫院'||title==='旅遊業的客戶'){p.id=CLIENT_IDS[title];p.projectType='client_root';delete p.parentProjectId;}else if(SITE_IDS[title]){p.id=SITE_IDS[title];p.parentProjectId=PARENT_ID;p.projectType='client_site';p.category='李總醫療體系｜據點';}}return out;}
function canonicalTasks(items:any[],projects:any[]){const valid=new Set(projects.map(p=>String(p.id)));const names=new Map(projects.map(p=>[String(p.id),String(p.title||'')]));const map=new Map<string,any>();for(const original of items){const t={...original};const site=inferLiSiteFromTask(String(t.title||''),String(t.notes||''));if(site)t.projectId=SITE_IDS[site];else{const title=String(t.projectName||'').trim();if(CLIENT_IDS[title])t.projectId=CLIENT_IDS[title];else if(SITE_IDS[title])t.projectId=SITE_IDS[title];}if(!valid.has(String(t.projectId||'')))continue;t.projectName=names.get(String(t.projectId))||t.projectName||'';const key=`${t.projectId}|${String(t.title||'').trim().toLowerCase()}`;const old=map.get(key);if(!old||String(t.notes||'').length>String(old.notes||'').length)map.set(key,t);}return Array.from(map.values());}
function parseDurationHours(x:string){const m=x.match(/(\d{1,2}):(\d{2})\s*-\s*(\d{1,2}):(\d{2})/);if(!m)return 1;const s=Number(m[1])*60+Number(m[2]),e=Number(m[3])*60+Number(m[4]);return Math.max(.5,Math.round(((e>=s?e-s:e+1440-s)/60)*10)/10);}
function todayDeadline(x:string){const m=x.match(/-\s*(\d{1,2}:\d{2})/);return`${new Date().toISOString().slice(0,10)} ${m?.[1]||'23:59'}`;}
export const DatabaseSync:React.FC=()=>{const data=useAppData();const hydrated=useRef(false);const configured=useRef(false);const syncing=useRef(false);const migrationDone=useRef(false);const processedScheduleKeys=useRef<Set<string>>(new Set());
useEffect(()=>{try{const saved=localStorage.getItem('ait_schedule_task_sync_v1');if(saved){const ids=JSON.parse(saved);if(Array.isArray(ids))ids.forEach((id:string)=>processedScheduleKeys.current.add(id));}}catch{}},[]);
useEffect(()=>{let cancelled=false;const bootstrap=async()=>{try{const health=await fetch(apiUrl('/api/persistence/health'),{headers:{'X-Owner-Id':OWNER_ID}}).then(r=>r.json());if(cancelled||!health?.configured){hydrated.current=true;return;}configured.current=true;const response=await fetch(apiUrl('/api/persistence/snapshot'),{headers:{'X-Owner-Id':OWNER_ID}});if(!response.ok)throw new Error(`database snapshot ${response.status}`);const payload=await response.json();const snapshot:Snapshot=payload?.data||{projects:[],tasks:[],studySubjects:[],todayBlocks:[]};if(cancelled)return;const lp=canonicalProjects(userOnly(data.workProjects)),lwt=canonicalTasks(userOnly(data.workTasks),lp),lst=userOnly(data.studyTasks),ls=userOnly(data.studySubjects),lb=userOnly(data.todayBlocks);const dbp=canonicalProjects(snapshot.projects.map(fromProject)),dbs=snapshot.studySubjects.map(fromSubject),dbw=canonicalTasks(snapshot.tasks.filter((t:any)=>t.domain==='work').map(fromWorkTask),dbp),dbst=snapshot.tasks.filter((t:any)=>t.domain==='study').map((t:any)=>fromStudyTask(t,dbs)),dbb=snapshot.todayBlocks.map(fromBlock);const hasLocal=lp.length+lwt.length+lst.length+ls.length+lb.length>0,hasDb=dbp.length+dbw.length+dbs.length+dbst.length+dbb.length>0;
if(!hasDb&&hasLocal&&!migrationDone.current){await fetch(apiUrl('/api/persistence/sync'),{method:'POST',headers:{'Content-Type':'application/json','X-Owner-Id':OWNER_ID},body:JSON.stringify({projects:lp,workTasks:lwt,studyTasks:lst,studySubjects:ls,todayBlocks:lb})});migrationDone.current=true;}else if(hasDb){const pi=new Set(dbp.map(p=>p.id)),wi=new Set(dbw.map(t=>t.id)),si=new Set(dbst.map(t=>t.id)),sui=new Set(dbs.map(s=>s.id));const mergedProjects=canonicalProjects([...dbp,...lp]);const mergedWorkTasks=canonicalTasks([...dbw,...lwt],mergedProjects);const mergedStudySubjects=[...dbs,...ls.filter(s=>!sui.has(s.id))];const mergedStudyTasks=[...dbst,...lst.filter(t=>!si.has(t.id))];
      for(const p of mergedProjects){const same=data.workProjects.find(x=>x.id===p.id);same?data.updateWorkProject(p):data.addWorkProject(p);}for(const t of mergedWorkTasks){const same=data.workTasks.find(x=>x.id===t.id);same?data.updateWorkTask(t):data.addWorkTask(t);}for(const s of mergedStudySubjects){const same=data.studySubjects.find(x=>x.id===s.id);same?data.updateStudySubject(s):data.addStudySubject(s);}for(const t of mergedStudyTasks){const same=data.studyTasks.find(x=>x.id===t.id);same?data.updateStudyTask(t):data.addStudyTask(t);}for(const b of dbb){data.todayBlocks.some(x=>x.id===b.id)?data.updateTodayBlock(b):data.addTodayBlock(b);}
      await fetch(apiUrl('/api/persistence/sync'),{method:'POST',headers:{'Content-Type':'application/json','X-Owner-Id':OWNER_ID},body:JSON.stringify({projects:mergedProjects,workTasks:mergedWorkTasks,studyTasks:mergedStudyTasks,studySubjects:mergedStudySubjects,todayBlocks:[...dbb,...lb.filter(b=>!snapshot.todayBlocks.some((x:any)=>String(x.id)===String(b.id)))]})});migrationDone.current=true;}hydrated.current=true;}catch(error){console.warn('[DatabaseSync] database unavailable; local fallback remains active.',error);hydrated.current=true;}};void bootstrap();return()=>{cancelled=true}},[]);
useEffect(()=>{if(!hydrated.current)return;const candidates=data.todayBlocks.filter(b=>b.type==='work'||b.type==='study');if(!candidates.length)return;const run=()=>{let changed=false;const now=Date.now(),ewi=new Set(data.workTasks.map(t=>t.id)),esi=new Set(data.studyTasks.map(t=>t.id)),ewt=new Set(data.workTasks.map(t=>`${t.title}|${t.deadline.slice(0,10)}`)),est=new Set(data.studyTasks.map(t=>`${t.title}|${t.deadline.slice(0,10)}`));const fp=data.workProjects.find(p=>p.source==='user')||data.workProjects[0],fs=data.studySubjects.find(s=>s.source==='user')||data.studySubjects[0];candidates.forEach((block,index)=>{const key=`${block.id}|${block.title}|${block.timeRange}`;if(processedScheduleKeys.current.has(key))return;const deadline=todayDeadline(block.timeRange),hours=parseDurationHours(block.timeRange),b:any=block;const priority:'high'|'medium'|'low'=b.priority||(b.visualPriority==='urgent'?'high':b.visualPriority==='important'?'medium':'low');if(block.type==='work'){if(ewi.has(block.id)||ewt.has(`${block.title}|${deadline.slice(0,10)}`)){processedScheduleKeys.current.add(key);return;}const category=classifyWorkTaskCategory(block.title,block.notes||''),categoryNote=category?`[工作分類] ${category.category}｜${category.item}\n${category.description}`:'[工作分類] 待 Manager Agent 分類';data.addWorkTask({id:`w-task-scheduled-${now}-${index}`,workspaceId:'work',projectId:data.currentContext.projectId||fp?.id||'proj-ai-scheduled',projectName:fp?.title||'AI 排程工作（待歸類）',title:block.title,priority,status:'todo',estimatedHours:hours,startDate:new Date().toISOString().slice(0,10),deadline,assignee:'本人',notes:`${categoryNote}\n[AIT_SCHEDULED] ${block.timeRange}\n[任務等級] ${priority==='high'?'迫切':priority==='medium'?'重要':'一般'}`,tags:['AI-SCHEDULED',...(category?[category.category,category.item]:[])],isUrgent:priority==='high',source:'user',createdBy:'user'});changed=true;}else if(!esi.has(block.id)&&!est.has(`${block.title}|${deadline.slice(0,10)}`)){data.addStudyTask({id:`s-task-scheduled-${now}-${index}`,subjectId:fs?.id||'subj-ai-scheduled',subjectName:fs?.name||'AI 排程課業（待歸類）',title:block.title,type:'study_task',chapter:'AI 排程',deadline,progress:0,estimatedHours:hours,priority,difficulty:'medium',status:'todo',supervisionNote:'由 Manager Agent 排程建立，請依時段執行。',notes:`[AIT_SCHEDULED] ${block.timeRange}\n[任務等級] ${priority==='high'?'迫切':priority==='medium'?'重要':'一般'}`,source:'user',createdBy:'user'});changed=true;}processedScheduleKeys.current.add(key);});if(changed)localStorage.setItem('ait_schedule_task_sync_v1',JSON.stringify(Array.from(processedScheduleKeys.current).slice(-300)));};const timer=window.setTimeout(run,250);return()=>window.clearTimeout(timer)},[data.todayBlocks,data.workTasks,data.studyTasks,data.workProjects,data.studySubjects,data.currentContext]);
useEffect(()=>{if(!hydrated.current)return;const research=data.workTasks.filter(t=>t.source==='user'&&/研究/.test(`${t.title} ${t.notes||''}`)&&/AI 對話|User-Created|由使用者透過 AI/.test(`${t.title} ${t.notes||''}`));if(!research.length)return;const timer=window.setTimeout(()=>research.forEach(task=>{const linked=`s-task-research-${task.id}`;if(data.studyTasks.some(t=>t.id===linked||t.notes?.includes(`[RESEARCH_LINK:${task.id}]`)))return;const fallback=data.studySubjects.find(s=>s.source==='user')||data.studySubjects[0];data.addStudyTask({id:linked,subjectId:fallback?.id||'subj-research',subjectName:fallback?.name||'研究／專題（待歸類）',title:task.title,type:'study_task',chapter:'研究任務',deadline:task.deadline||'',progress:0,estimatedHours:Number(task.estimatedHours)||1,priority:task.priority,difficulty:'medium',status:task.status==='completed'?'completed':'todo',supervisionNote:'由 Manager Agent 建立的研究任務，已同步至課業任務。',notes:`由 Manager Agent 建立之研究任務。\n[RESEARCH_LINK:${task.id}]`,source:'user',createdBy:'user'});}),100);return()=>window.clearTimeout(timer)},[data.workTasks,data.studyTasks,data.studySubjects]);
useEffect(()=>{if(!configured.current||!hydrated.current||syncing.current)return;const timer=window.setTimeout(async()=>{syncing.current=true;try{const projects=canonicalProjects(userOnly(data.workProjects)),workTasks=canonicalTasks(userOnly(data.workTasks),projects);await fetch(apiUrl('/api/persistence/sync'),{method:'POST',headers:{'Content-Type':'application/json','X-Owner-Id':OWNER_ID},body:JSON.stringify({projects,workTasks,studyTasks:userOnly(data.studyTasks),studySubjects:userOnly(data.studySubjects),todayBlocks:userOnly(data.todayBlocks)})});}catch(error){console.warn('[DatabaseSync] sync failed; local state retained.',error)}finally{syncing.current=false}},SYNC_DELAY);return()=>window.clearTimeout(timer)},[data.workProjects,data.workTasks,data.studySubjects,data.studyTasks,data.todayBlocks]);return null;};
export default DatabaseSync;
