import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Archive,CheckCircle2,Home,Link2,Plus,RotateCcw,Trash2,MessageCircle} from 'lucide-react';
import type {IdeaBoardData,IdeaEdge,IdeaNode} from '../types/ideaBoard';
import {createIdeaEdge,createIdeaNode} from '../types/ideaBoard';
import {apiUrl} from '../services/apiBase';
const STORAGE_KEY='ait_idea_boards_v1'; const BOARD_ID='main-idea-board'; const WIDTH=1800; const HEIGHT=1100;
const initialBoard=():IdeaBoardData=>({id:BOARD_ID,name:'我的想法白板',description:'把零散想法留下來，讓 Manager 每天一起整理：保留、轉成任務，或歸檔。',nodes:[],edges:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
const loadLocal=():IdeaBoardData=>{try{const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):initialBoard()}catch{return initialBoard()}};
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
export const IdeaBoard:React.FC=()=>{
 const [board,setBoard]=useState<IdeaBoardData>(loadLocal); const [selectedId,setSelectedId]=useState<string|null>(null); const [connectingFrom,setConnectingFrom]=useState<string|null>(null); const [dragging,setDragging]=useState<{id:string;offsetX:number;offsetY:number}|null>(null); const [pan]=useState({x:0,y:0}); const [showArchived,setShowArchived]=useState(false); const canvasRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{let cancelled=false;(async()=>{try{const r=await fetch(apiUrl('/api/persistence/idea-board'),{headers:{'X-Owner-Id':'personal-owner'}});if(!r.ok)return;const data=await r.json();if(cancelled||!data?.board)return;const local=loadLocal();const remote=data.board as IdeaBoardData;const chosen=new Date(remote.updatedAt||0).getTime()>new Date(local.updatedAt||0).getTime()?remote:local;setBoard(chosen);localStorage.setItem(STORAGE_KEY,JSON.stringify(chosen))}catch{}})();return()=>{cancelled=true}},[]);
 useEffect(()=>{const next={...board,updatedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,JSON.stringify(next));const timer=window.setTimeout(()=>{void fetch(apiUrl('/api/persistence/idea-board'),{method:'POST',headers:{'Content-Type':'application/json','X-Owner-Id':'personal-owner'},body:JSON.stringify({board:next})}).catch(()=>undefined)},500);return()=>window.clearTimeout(timer)},[board]);
 const selected=useMemo(()=>board.nodes.find(n=>n.id===selectedId)||null,[board.nodes,selectedId]);
 const updateNode=(id:string,updates:Partial<IdeaNode>)=>setBoard(prev=>({...prev,nodes:prev.nodes.map(n=>n.id===id?{...n,...updates,updatedAt:new Date().toISOString()}:n)}));
 const addNode=()=>{const n=createIdeaNode(BOARD_ID,'新想法',300-pan.x,220-pan.y);setBoard(prev=>({...prev,nodes:[...prev.nodes,n]}));setSelectedId(n.id)};
 const deleteSelected=()=>{if(!selectedId)return;setBoard(prev=>({...prev,nodes:prev.nodes.filter(n=>n.id!==selectedId),edges:prev.edges.filter(e=>e.fromNodeId!==selectedId&&e.toNodeId!==selectedId)}));setSelectedId(null);setConnectingFrom(null)};
 const archiveSelected=()=>{if(!selected)return;updateNode(selected.id,{status:'archived',archivedAt:new Date().toISOString()});setSelectedId(null)};
 const restoreSelected=()=>{if(!selected)return;updateNode(selected.id,{status:'idea',archivedAt:undefined});};
 const connectNode=(targetId:string)=>{if(!connectingFrom||connectingFrom===targetId)return setConnectingFrom(null);const exists=board.edges.some(e=>(e.fromNodeId===connectingFrom&&e.toNodeId===targetId)||(e.fromNodeId===targetId&&e.toNodeId===connectingFrom));if(!exists)setBoard(prev=>({...prev,edges:[...prev.edges,createIdeaEdge(BOARD_ID,connectingFrom,targetId)]}));setConnectingFrom(null)};
 const startDrag=(event:React.PointerEvent,node:IdeaNode)=>{event.stopPropagation();const rect=canvasRef.current?.getBoundingClientRect();if(!rect)return;setSelectedId(node.id);setDragging({id:node.id,offsetX:event.clientX-rect.left-node.x-pan.x,offsetY:event.clientY-rect.top-node.y-pan.y});(event.currentTarget as HTMLElement).setPointerCapture(event.pointerId)};
 const moveDrag=(event:React.PointerEvent)=>{if(!dragging)return;const rect=canvasRef.current?.getBoundingClientRect();if(!rect)return;updateNode(dragging.id,{x:clamp(event.clientX-rect.left-dragging.offsetX-pan.x,20,WIDTH-260),y:clamp(event.clientY-rect.top-dragging.offsetY-pan.y,20,HEIGHT-150)})};
 const nodeCenter=(n:IdeaNode)=>({x:n.x+105,y:n.y+45});
 const reset=()=>{setBoard(initialBoard());setSelectedId(null);setConnectingFrom(null)};
 const reviewToday=()=>{const active=board.nodes.filter(n=>n.status!=='archived');setBoard(prev=>({...prev,lastManagerReviewAt:new Date().toISOString(),nodes:prev.nodes.map(n=>n.status==='archived'?n:{...n,lastReviewedAt:new Date().toISOString()})}));window.dispatchEvent(new CustomEvent('ait:manager-idea-review',{detail:{prompt:`今天請你和我整理「想法白板」。目前有 ${active.length} 個未歸檔想法。請逐一判斷：1. 保留在白板持續討論 2. 轉成工作/研究/學習任務 3. 已沒有價值就歸檔。不要自行刪除想法；先跟我確認哪些要歸檔或轉任務。`}}))};
 const visible=board.nodes.filter(n=>showArchived?n.status==='archived':n.status!=='archived');
 return <div className="h-full min-h-[620px] flex flex-col bg-[#F5F3EE] rounded-2xl border border-[#E5E2DC] overflow-hidden">
  <div className="px-4 py-3 bg-white border-b border-[#E5E2DC] flex items-center justify-between gap-3"><div><div className="font-bold text-sm text-[#2D322E]">☁️ 想法白板</div><div className="text-[10px] text-[#8C938D]">每天和 Manager 一起整理：留下來、轉成任務，或歸檔。</div></div><div className="flex items-center gap-1.5 flex-wrap justify-end"><button onClick={reviewToday} className="px-3 py-2 rounded-lg bg-[#385244] text-white text-xs flex items-center gap-1"><MessageCircle className="w-3.5 h-3.5"/>今日與 Manager 整理</button><button onClick={()=>setShowArchived(v=>!v)} className="px-3 py-2 rounded-lg border border-[#DDD8CE] bg-white text-xs flex items-center gap-1"><Archive className="w-3.5 h-3.5"/>{showArchived?'返回進行中':'查看已歸檔'}</button><button onClick={addNode} className="px-3 py-2 rounded-lg bg-[#385244] text-white text-xs flex items-center gap-1"><Plus className="w-3.5 h-3.5"/>新增想法</button><button onClick={()=>selectedId&&setConnectingFrom(selectedId)} disabled={!selectedId} className="px-3 py-2 rounded-lg border border-[#DDD8CE] bg-white text-xs disabled:opacity-40 flex items-center gap-1"><Link2 className="w-3.5 h-3.5"/>連結</button><button onClick={deleteSelected} disabled={!selectedId} className="p-2 rounded-lg border border-[#DDD8CE] disabled:opacity-40"><Trash2 className="w-3.5 h-3.5"/></button><button onClick={reset} className="p-2 rounded-lg border border-[#DDD8CE]" title="清空白板"><RotateCcw className="w-3.5 h-3.5"/></button></div></div>
  <div className="flex-1 flex min-h-0"><div ref={canvasRef} onPointerMove={moveDrag} onPointerUp={()=>setDragging(null)} className="relative flex-1 overflow-hidden bg-[radial-gradient(#d9d5cc_1px,transparent_1px)] [background-size:22px_22px]"><svg className="absolute inset-0 w-full h-full pointer-events-none">{board.edges.map(e=>{const a=board.nodes.find(n=>n.id===e.fromNodeId),b=board.nodes.find(n=>n.id===e.toNodeId);if(!a||!b)return null;const p1=nodeCenter(a),p2=nodeCenter(b);return <line key={e.id} x1={p1.x+pan.x} y1={p1.y+pan.y} x2={p2.x+pan.x} y2={p2.y+pan.y} stroke="#A9B9AD" strokeWidth="3" strokeDasharray="7 5"/>})}</svg>{visible.map(n=><div key={n.id} onPointerDown={e=>startDrag(e,n)} onDoubleClick={()=>updateNode(n.id,{status:n.status==='completed'?'idea':'completed'})} onClick={()=>connectingFrom?connectNode(n.id):setSelectedId(n.id)} style={{left:n.x+pan.x,top:n.y+pan.y}} className={`absolute w-[210px] min-h-[90px] p-3 rounded-2xl border-2 shadow-md cursor-grab select-none ${selectedId===n.id?'border-[#385244] ring-2 ring-[#BCD2C3]':'border-[#DDD8CE]'} ${n.status==='completed'?'bg-[#E7F1E9]':'bg-[#FFFDF8]'}`}><div className="flex items-center justify-between gap-2"><span className="text-[10px] text-[#8C938D]">{n.status==='completed'?'🏠 已完成':n.status==='archived'?'📦 已歸檔':'☁️ 想法'}</span>{n.status==='completed'&&<CheckCircle2 className="w-4 h-4 text-[#385244]"/>}</div><div className="font-semibold text-sm text-[#2D322E] mt-1 break-words">{n.title}</div>{n.note&&<div className="text-[10px] text-[#6B726C] mt-1 break-words">{n.note}</div>}</div>)}{!visible.length&&<div className="absolute inset-0 flex items-center justify-center text-center"><div><div className="text-5xl mb-3">{showArchived?'📦':'☁️'}</div><div className="font-bold text-sm text-[#555D57]">{showArchived?'目前沒有已歸檔想法':'把第一個想法放上來'}</div></div></div>}</div>
  <aside className="hidden lg:flex w-72 shrink-0 bg-white border-l border-[#E5E2DC] p-4 flex-col gap-4">{selected?<><div><div className="text-[10px] text-[#8C938D]">選取的想法</div><input value={selected.title} onChange={e=>updateNode(selected.id,{title:e.target.value})} className="mt-1 w-full px-2.5 py-2 rounded-lg border border-[#DDD8CE] text-sm"/></div><div><div className="text-[10px] text-[#8C938D]">備註</div><textarea value={selected.note||''} onChange={e=>updateNode(selected.id,{note:e.target.value})} className="mt-1 w-full h-24 px-2.5 py-2 rounded-lg border border-[#DDD8CE] text-xs resize-none" placeholder="補充這個想法…"/></div>{selected.status==='archived'?<button onClick={restoreSelected} className="w-full px-3 py-2 rounded-lg bg-[#E8EFEB] text-[#385244] text-xs font-semibold">恢復到白板</button>:<button onClick={archiveSelected} className="w-full px-3 py-2 rounded-lg bg-[#F1ECE3] text-[#705A36] text-xs font-semibold flex items-center justify-center gap-1"><Archive className="w-3.5 h-3.5"/>歸檔這個想法</button>}<button onClick={()=>updateNode(selected.id,{status:selected.status==='completed'?'idea':'completed',kind:selected.status==='completed'?'idea':'project'})} className="w-full px-3 py-2 rounded-lg bg-[#E8EFEB] text-[#385244] text-xs font-semibold flex items-center justify-center gap-1"><Home className="w-3.5 h-3.5"/>{selected.status==='completed'?'退回想法':'標記為完成成果'}</button><div className="text-[10px] text-[#8C938D] leading-relaxed">Manager 每日整理時只提出建議，不會偷偷刪除。你確認後才歸檔或轉成任務。</div></>:<div className="text-xs text-[#8C938D] leading-relaxed">選取一個想法後，可以編輯、建立關聯、歸檔。白板資料同時保存在瀏覽器與共享資料庫。</div>}<div className="mt-auto text-[10px] text-[#A0A59F]">{board.lastManagerReviewAt?`上次 Manager 整理：${new Date(board.lastManagerReviewAt).toLocaleString('zh-TW')}`:'今天尚未與 Manager 整理'}</div></aside></div></div>;
};
export default IdeaBoard;
