import React, { useMemo, useState } from 'react';
import { CheckCircle2, ClipboardCheck, Sun, Moon, ArrowRight, Clock3, PauseCircle, Check } from 'lucide-react';
import type { WorkTask, StudyTask } from '../types';

type Task = WorkTask | StudyTask;
type Mode = 'daily-review' | 'tomorrow-plan';
type Decision = 'continue' | 'delay' | 'pause' | 'complete';
interface Props { mode: Mode; workTasks: WorkTask[]; studyTasks: StudyTask[]; onConfirm: (message: string) => void; }
const priorityWeight: Record<string, number> = { high: 3, medium: 2, low: 1 };
const statusLabel: Record<string, string> = { todo:'待辦', in_progress:'進行中', delayed:'延遲', completed:'已完成' };
const decisionMeta: Record<Decision,{label:string;icon:React.ReactNode}> = {
 continue:{label:'明天繼續',icon:<Check className="w-3 h-3"/>},
 delay:{label:'延後',icon:<Clock3 className="w-3 h-3"/>},
 pause:{label:'暫停',icon:<PauseCircle className="w-3 h-3"/>},
 complete:{label:'完成',icon:<CheckCircle2 className="w-3 h-3"/>},
};
function formatDeadline(value:string){if(!value)return'未設定';const date=new Date(value);if(Number.isNaN(date.getTime()))return value;return date.toLocaleString('zh-TW',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});}
export const ManagerChecklist:React.FC<Props>=({mode,workTasks,studyTasks,onConfirm})=>{
 const tasks=useMemo<Task[]>(()=>[...workTasks.filter(t=>t.source==='user').map(t=>({...t,_domain:'💼 工作'})),...studyTasks.filter(t=>t.source==='user').map(t=>({...t,_domain:'🎓 課業／研究'}))].sort((a,b)=>(priorityWeight[b.priority]||0)-(priorityWeight[a.priority]||0)||new Date(a.deadline).getTime()-new Date(b.deadline).getTime()) as Task[],[workTasks,studyTasks]);
 const pending=tasks.filter(t=>t.status!=='completed'); const completed=tasks.filter(t=>t.status==='completed');
 const [decisions,setDecisions]=useState<Record<string,Decision>>(()=>Object.fromEntries(pending.map(t=>[t.id,'continue']))); const [confirmed,setConfirmed]=useState(false);
 const setDecision=(id:string,d:Decision)=>{setDecisions(prev=>({...prev,[id]:d}));setConfirmed(false);};
 const confirm=()=>{const groups:Record<Decision,string[]>={continue:[],delay:[],pause:[],complete:[]};pending.forEach(t=>groups[decisions[t.id]||'continue'].push(`${t.title}（${t.id}）`));setConfirmed(true);const lines=[groups.continue.length?`明天繼續：${groups.continue.join('、')}`:'',groups.delay.length?`延後：${groups.delay.join('、')}`:'',groups.pause.length?`暫停：${groups.pause.join('、')}`:'',groups.complete.length?`確認完成：${groups.complete.join('、')}`:''].filter(Boolean).join('；');onConfirm(mode==='daily-review'?`我確認每日覆盤決策。${lines||'沒有需要安排的任務。'}`:`我確認明日規劃。${lines||'沒有需要安排的任務。'}`);};
 return <section className="mt-3 rounded-2xl border-2 border-[#C9DCCF] bg-white overflow-hidden shadow-sm">
  <div className="px-4 py-3 bg-[#EAF2EC] border-b border-[#D5E3D9] flex items-center gap-3"><div className="w-9 h-9 rounded-lg bg-[#385244] text-white flex items-center justify-center">{mode==='daily-review'?<Moon className="w-4 h-4"/>:<Sun className="w-4 h-4"/>}</div><div className="min-w-0 flex-1"><div className="font-bold text-sm text-[#26362C]">{mode==='daily-review'?'🌙 每日覆盤｜逐項決策':'☀️ 隔日規劃｜Owner 審核清單'}</div><div className="text-[10px] text-[#6B726C] mt-0.5">{mode==='daily-review'?'每個任務都可選擇：明天繼續、延後、暫停或確認完成。':'Manager 依優先級與截止時間整理候選任務；選擇後才送出確認。'}</div></div></div>
  <div className="p-4"><div className="grid grid-cols-3 gap-2 mb-3"><div className="rounded-xl bg-[#F7F5F1] p-2.5 text-center"><div className="text-lg font-bold text-[#385244]">{completed.length}</div><div className="text-[10px] text-[#7A837D]">已完成</div></div><div className="rounded-xl bg-[#F7F5F1] p-2.5 text-center"><div className="text-lg font-bold text-[#7D3E1B]">{pending.length}</div><div className="text-[10px] text-[#7A837D]">待決策</div></div><div className="rounded-xl bg-[#F7F5F1] p-2.5 text-center"><div className="text-lg font-bold text-[#385244]">{Object.values(decisions).filter(d=>d==='continue').length}</div><div className="text-[10px] text-[#7A837D]">明天繼續</div></div></div>
   <div className="flex items-center justify-between mb-2"><span className="text-xs font-bold text-[#3F4440]">{mode==='daily-review'?'今日未完成任務':'明日候選任務'}</span><span className="text-[10px] text-[#7A837D]">每項任務請選一個處理方式</span></div>
   <div className="space-y-2 max-h-80 overflow-y-auto pr-1">{pending.length===0?<div className="py-5 text-center text-xs text-[#6B726C]">🎉 目前沒有未完成的 User Task。</div>:pending.map(task=>{const decision=decisions[task.id]||'continue';return <div key={task.id} className="p-3 rounded-xl border border-[#E5E2DC] bg-white"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><div className="flex items-center gap-1.5 flex-wrap"><span className="text-xs font-semibold text-[#2D322E]">{task.title}</span><span className="text-[9px] px-1.5 py-0.5 rounded-full bg-[#EFECE5] text-[#6B726C]">{'_domain'in task?(task as any)._domain:'任務'}</span><span className="text-[9px] px-1.5 py-0.5 rounded-full bg-[#FAF0E6] text-[#7D3E1B]">{statusLabel[task.status]||task.status}</span></div><div className="mt-1 text-[10px] text-[#7A837D]">優先級：{task.priority}　·　截止：{formatDeadline(task.deadline)}　·　預估：{task.estimatedHours}h</div></div></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-1.5 mt-2">{(Object.keys(decisionMeta) as Decision[]).map(d=><button key={d} type="button" onClick={()=>setDecision(task.id,d)} className={`inline-flex items-center justify-center gap-1 px-2 py-1.5 rounded-lg border text-[10px] font-medium transition-colors ${decision===d?'bg-[#E8EFEB] border-[#9FBEA8] text-[#385244]':'bg-white border-[#DEDAD2] text-[#6B726C] hover:bg-[#F7F5F1]'}`}>{decisionMeta[d].icon}{decisionMeta[d].label}</button>)}</div></div>;})}</div>
   <div className="mt-3 flex items-center justify-between gap-2 pt-3 border-t border-[#EBE8E1]"><div className="text-[10px] text-[#7A837D] flex items-center gap-1"><ClipboardCheck className="w-3.5 h-3.5"/>決策先交給 Manager，不會因選擇直接修改任務。</div><button type="button" onClick={confirm} disabled={confirmed} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-[#385244] text-white text-xs font-semibold disabled:opacity-60">{confirmed?<CheckCircle2 className="w-3.5 h-3.5"/>:<ArrowRight className="w-3.5 h-3.5"/>}{confirmed?'已送出確認':'送出覆盤決策'}</button></div>
  </div></section>;
};