import React, { useState } from 'react';
import { Briefcase, Plus, CheckCircle2, Clock, FolderKanban, Sparkles, Flame, Trash2, Edit2, FolderPlus, ArrowRight } from 'lucide-react';
import { WorkProject, WorkTask } from '../types';
import WorkProjectDetail from './WorkProjectDetail';

interface WorkViewProps {
  projects: WorkProject[]; tasks: WorkTask[];
  onToggleTask: (taskId: string) => void;
  onAddTask: (task: Omit<WorkTask, 'id'>) => void;
  onUpdateTask: (task: WorkTask) => void;
  onDeleteTask: (taskId: string) => void;
  onAddProject: (project: Omit<WorkProject, 'id'>) => void;
  onUpdateProject: (project: WorkProject) => void;
  onDeleteProject: (projectId: string) => void;
  onAskAgentAboutWork: (prompt: string) => void;
  onClearDemoData?: () => void;
}

export const WorkView: React.FC<WorkViewProps> = ({ projects, tasks, onToggleTask, onAddTask, onUpdateTask, onDeleteTask, onAddProject, onUpdateProject, onDeleteProject, onAskAgentAboutWork, onClearDemoData }) => {
  const [selectedProjectId, setSelectedProjectId] = useState<string | null>(null);
  const [filterSource, setFilterSource] = useState<'ALL' | 'user' | 'demo'>('ALL');
  const [filterPriority, setFilterPriority] = useState<'ALL' | 'high' | 'medium' | 'low'>('ALL');
  const [filterStatus, setFilterStatus] = useState<'ALL' | 'todo' | 'in_progress' | 'completed' | 'delayed'>('ALL');
  const [filterProject, setFilterProject] = useState('ALL');
  const [showTaskModal, setShowTaskModal] = useState(false);
  const [editingTask, setEditingTask] = useState<WorkTask | null>(null);
  const [taskTitle, setTaskTitle] = useState(''); const [taskProjectId, setTaskProjectId] = useState(''); const [taskPriority, setTaskPriority] = useState<'high'|'medium'|'low'>('high'); const [taskStatus, setTaskStatus] = useState<'todo'|'in_progress'|'completed'|'delayed'>('todo'); const [taskHours, setTaskHours] = useState(2); const [taskStartDate, setTaskStartDate] = useState(''); const [taskDeadline, setTaskDeadline] = useState(''); const [taskAssignee, setTaskAssignee] = useState('本人'); const [taskNotes, setTaskNotes] = useState(''); const [taskIsUrgent, setTaskIsUrgent] = useState(false);
  const [showProjectModal, setShowProjectModal] = useState(false); const [editingProject, setEditingProject] = useState<WorkProject | null>(null);
  const [projectTitle, setProjectTitle] = useState(''); const [projectCategory, setProjectCategory] = useState('專案'); const [projectPriority, setProjectPriority] = useState<'high'|'medium'|'low'>('high'); const [projectStatus, setProjectStatus] = useState<'planning'|'in_progress'|'completed'|'on_hold'>('in_progress'); const [projectProgress, setProjectProgress] = useState(0); const [projectDeadline, setProjectDeadline] = useState(''); const [projectOwner, setProjectOwner] = useState('本人'); const [projectDescription, setProjectDescription] = useState(''); const [projectTags, setProjectTags] = useState('');

  const openCreateTaskModal = (projectId = selectedProjectId || projects[0]?.id || '') => { setEditingTask(null); setTaskTitle(''); setTaskProjectId(projectId); setTaskPriority('high'); setTaskStatus('todo'); setTaskHours(2); setTaskStartDate(new Date().toISOString().slice(0,10)); setTaskDeadline(''); setTaskAssignee('本人'); setTaskNotes(''); setTaskIsUrgent(false); setShowTaskModal(true); };
  const openEditTaskModal = (t: WorkTask) => { setEditingTask(t); setTaskTitle(t.title); setTaskProjectId(t.projectId || ''); setTaskPriority(t.priority); setTaskStatus(t.status); setTaskHours(t.estimatedHours); setTaskStartDate(t.startDate || ''); setTaskDeadline(t.deadline || ''); setTaskAssignee(t.assignee || '本人'); setTaskNotes(t.notes || ''); setTaskIsUrgent(Boolean(t.isUrgent)); setShowTaskModal(true); };
  const saveTask = (e: React.FormEvent) => { e.preventDefault(); if (!taskTitle.trim()) return; const p=projects.find(x=>x.id===taskProjectId); const base={title:taskTitle.trim(),workspaceId:'work',projectId:taskProjectId,projectName:p?.title||'未歸類專案',priority:taskPriority,status:taskStatus,estimatedHours:Number(taskHours)||1,startDate:taskStartDate.trim(),deadline:taskDeadline.trim(),assignee:taskAssignee.trim()||'本人',notes:taskNotes.trim(),isUrgent:taskIsUrgent,tags:[taskPriority.toUpperCase()],source:'user' as const,createdBy:'user' as const}; if(editingTask) onUpdateTask({...editingTask,...base}); else onAddTask(base); setShowTaskModal(false); };
  const openCreateProjectModal=()=>{setEditingProject(null);setProjectTitle('');setProjectCategory('專案');setProjectPriority('high');setProjectStatus('in_progress');setProjectProgress(0);setProjectDeadline('');setProjectOwner('本人');setProjectDescription('');setProjectTags('');setShowProjectModal(true);};
  const openEditProjectModal=(p:WorkProject)=>{setEditingProject(p);setProjectTitle(p.title);setProjectCategory(p.category);setProjectPriority(p.priority);setProjectStatus(p.status);setProjectProgress(p.progress);setProjectDeadline(p.deadline);setProjectOwner(p.owner||'本人');setProjectDescription(p.description);setProjectTags((p.tags||[]).join(', '));setShowProjectModal(true);};
  const saveProject=(e:React.FormEvent)=>{e.preventDefault();if(!projectTitle.trim())return;const base={title:projectTitle.trim(),workspaceId:'work',category:projectCategory.trim(),priority:projectPriority,status:projectStatus,progress:Number(projectProgress)||0,deadline:projectDeadline.trim(),owner:projectOwner.trim()||'本人',description:projectDescription.trim(),tags:projectTags.split(',').map(x=>x.trim()).filter(Boolean),source:'user' as const,createdBy:'user' as const};if(editingProject)onUpdateProject({...editingProject,...base});else onAddProject(base);setShowProjectModal(false);};

  const filteredProjects=projects.filter(p=>filterSource==='ALL'||p.source===filterSource);
  const filteredTasks=tasks.filter(t=>(filterSource==='ALL'||t.source===filterSource)&&(filterPriority==='ALL'||t.priority===filterPriority)&&(filterStatus==='ALL'||t.status===filterStatus)&&(filterProject==='ALL'||t.projectId===filterProject));
  const totalHours=tasks.filter(t=>t.status!=='completed').reduce((a,t)=>a+(Number(t.estimatedHours)||0),0);
  const selected=selectedProjectId ? projects.find(p=>p.id===selectedProjectId) : null;
  if(selected) return <WorkProjectDetail project={selected} tasks={tasks} onBack={()=>setSelectedProjectId(null)} onToggleTask={onToggleTask} onEditProject={openEditProjectModal} onEditTask={openEditTaskModal} onAddTask={()=>openCreateTaskModal(selected.id)} />;

  return <div className="max-w-6xl mx-auto px-4 sm:px-6 py-6 space-y-6">
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 p-5 rounded-2xl bg-white border border-[#E5E2DC] shadow-xs"><div><div className="flex items-center gap-2 mb-1"><span className="p-1.5 rounded-lg bg-[#EBF1EC] text-[#385244]"><Briefcase className="w-5 h-5"/></span><h2 className="text-lg font-bold">Work 專案與工作任務管理</h2><span className="px-2 py-0.5 rounded-full text-xs bg-[#EBF1EC] text-[#2D4835] border border-[#C6DAC9]">Work Agent 專屬資料庫</span></div><p className="text-xs sm:text-sm text-[#6B726C]">每個專案都可點入查看完整工作項目與執行細節。</p></div><div className="flex flex-wrap gap-2">{onClearDemoData&&(projects.some(p=>p.source==='demo')||tasks.some(t=>t.source==='demo'))&&<button onClick={onClearDemoData} className="px-3 py-2 rounded-xl bg-[#FAF0E6] text-[#B36534] text-xs font-semibold">清除示範資料</button>}<button onClick={()=>onAskAgentAboutWork('請 Work Agent 分析目前所有工作任務的優先級與截止日，並給出執行建議。')} className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-[#EFECE5] text-[#385244] text-xs font-semibold"><Sparkles className="w-4 h-4"/>呼叫 Work Agent 分析</button><button onClick={openCreateProjectModal} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl border border-[#DDD8CE] text-[#385244] text-xs font-semibold"><FolderPlus className="w-4 h-4"/>新增專案</button><button onClick={()=>openCreateTaskModal()} className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-[#385244] text-white text-xs font-semibold"><Plus className="w-4 h-4"/>新增工作任務</button></div></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div className="p-4 rounded-xl bg-white border border-[#E5E2DC]"><span className="text-xs text-[#6B726C]">真實登記專案</span><div className="text-xl font-bold mt-1">{projects.length} 個專案</div></div><div className="p-4 rounded-xl bg-white border border-[#E5E2DC]"><span className="text-xs text-[#6B726C]">待辦與進行中任務</span><div className="text-xl font-bold text-[#4E6B56] mt-1">{tasks.filter(t=>t.status!=='completed').length} / {tasks.length} 項</div></div><div className="p-4 rounded-xl bg-white border border-[#E5E2DC]"><span className="text-xs text-[#6B726C]">預估待投入總工時</span><div className="text-xl font-bold text-[#B36534] mt-1">~{totalHours.toFixed(1)} 小時</div></div></div>
    <section className="p-5 rounded-2xl bg-white border border-[#E5E2DC] shadow-xs"><div className="flex items-center justify-between mb-4 pb-2 border-b border-[#EBE8E1]"><div className="flex items-center gap-2"><FolderKanban className="w-4 h-4 text-[#385244]"/><h3 className="text-sm font-bold">工作專案清單</h3></div><span className="text-xs text-[#6B726C]">{filteredProjects.length} 個專案</span></div>{filteredProjects.length===0?<div className="text-center py-10 text-sm text-[#6B726C]">目前尚未建立任何工作專案</div>:<div className="grid grid-cols-1 md:grid-cols-3 gap-4">{filteredProjects.map(p=>{const pt=tasks.filter(t=>t.projectId===p.id);const done=pt.filter(t=>t.status==='completed').length;const progress=pt.length?Math.round(done/pt.length*100):p.progress;return <button type="button" key={p.id} onClick={()=>setSelectedProjectId(p.id)} className="text-left p-4 rounded-xl bg-white border border-[#E5E2DC] hover:border-[#4E6B56] hover:shadow-md transition-all group"><div className="flex items-center justify-between mb-3"><span className="px-2 py-0.5 rounded bg-[#EBF1EC] text-[#2D4835] text-[10px] font-semibold">{p.category}</span><ArrowRight className="w-4 h-4 text-[#A39E93] group-hover:text-[#385244]"/></div><h4 className="text-sm font-bold text-[#2D322E]">{p.title}</h4><p className="text-xs text-[#6B726C] mt-1 line-clamp-2">{p.description||'無描述'}</p><div className="mt-4 flex items-center justify-between text-[10px] text-[#7A837D]"><span>{pt.length} 個工作項目</span><span>{done} 已完成</span></div><div className="mt-2 h-2 rounded-full bg-[#EFECE5] overflow-hidden"><div className="h-full bg-[#4E6B56] rounded-full" style={{width:`${progress}%`}}/></div><div className="mt-2 flex justify-between text-[10px] text-[#8C938D]"><span>進度 {progress}%</span><span>截止 {p.deadline||'未設定'}</span></div><div className="mt-3 text-[10px] font-semibold text-[#385244]">點擊查看詳細工作 →</div></button>})}</div>}</section>
    <section className="p-5 rounded-2xl bg-white border border-[#E5E2DC] shadow-xs"><div className="flex flex-wrap items-center gap-2 mb-3"><h3 className="text-sm font-bold mr-auto">全部工作任務</h3><select value={filterProject} onChange={e=>setFilterProject(e.target.value)} className="border border-[#DDD8CE] rounded-lg px-2 py-1 text-xs"><option value="ALL">全部專案</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><select value={filterPriority} onChange={e=>setFilterPriority(e.target.value as any)} className="border border-[#DDD8CE] rounded-lg px-2 py-1 text-xs"><option value="ALL">全部優先級</option><option value="high">迫切</option><option value="medium">重要</option><option value="low">一般</option></select><select value={filterStatus} onChange={e=>setFilterStatus(e.target.value as any)} className="border border-[#DDD8CE] rounded-lg px-2 py-1 text-xs"><option value="ALL">全部狀態</option><option value="todo">待辦</option><option value="in_progress">進行中</option><option value="completed">已完成</option><option value="delayed">已延遲</option></select></div><div className="space-y-2">{filteredTasks.map(t=><div key={t.id} className="p-3 rounded-xl border border-[#E5E2DC] flex items-center gap-3"><button onClick={()=>onToggleTask(t.id)}>{t.status==='completed'?<CheckCircle2 className="w-5 h-5 text-[#4E6B56]"/>:<Clock className="w-5 h-5 text-[#A39E93]"/>}</button><div className="min-w-0 flex-1"><div className="text-xs font-semibold">{t.title}</div><div className="text-[10px] text-[#8C938D] mt-1">{t.projectName||'未歸類'} · {t.priority==='high'?'迫切':t.priority==='medium'?'重要':'一般'} · {t.status==='completed'?'已完成':t.status==='in_progress'?'進行中':t.status==='delayed'?'已延遲':'待辦'} · {t.deadline||'無截止日'}</div></div><button onClick={()=>openEditTaskModal(t)} className="p-1.5 text-[#8C938D] hover:text-[#385244]"><Edit2 className="w-3.5 h-3.5"/></button></div>)}</div></section>
    {showProjectModal&&<div className="fixed inset-0 z-50 bg-black/30 flex items-center justify-center p-4"><form onSubmit={saveProject} className="w-full max-w-lg bg-white rounded-2xl p-5 space-y-3"><h3 className="font-bold">{editingProject?'編輯專案':'新增專案'}</h3><input value={projectTitle} onChange={e=>setProjectTitle(e.target.value)} placeholder="專案名稱" className="w-full border rounded-lg p-2 text-sm" required/><input value={projectCategory} onChange={e=>setProjectCategory(e.target.value)} placeholder="分類" className="w-full border rounded-lg p-2 text-sm"/><textarea value={projectDescription} onChange={e=>setProjectDescription(e.target.value)} placeholder="專案描述" className="w-full border rounded-lg p-2 text-sm"/><div className="grid grid-cols-2 gap-2"><select value={projectPriority} onChange={e=>setProjectPriority(e.target.value as any)} className="border rounded-lg p-2 text-sm"><option value="high">迫切</option><option value="medium">重要</option><option value="low">一般</option></select><input type="date" value={projectDeadline} onChange={e=>setProjectDeadline(e.target.value)} className="border rounded-lg p-2 text-sm"/></div><div className="flex justify-end gap-2"><button type="button" onClick={()=>setShowProjectModal(false)} className="px-3 py-2 border rounded-lg text-sm">取消</button><button className="px-3 py-2 bg-[#385244] text-white rounded-lg text-sm">儲存</button></div></form></div>}
    {showTaskModal&&<div className="fixed inset-0 z-50 bg-black/30 flex items-center justify-center p-4"><form onSubmit={saveTask} className="w-full max-w-lg bg-white rounded-2xl p-5 space-y-3"><h3 className="font-bold">{editingTask?'編輯工作':'新增工作'}</h3><input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="工作項目名稱" className="w-full border rounded-lg p-2 text-sm" required/><select value={taskProjectId} onChange={e=>setTaskProjectId(e.target.value)} className="w-full border rounded-lg p-2 text-sm"><option value="">未歸類專案</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><div className="grid grid-cols-2 gap-2"><select value={taskPriority} onChange={e=>setTaskPriority(e.target.value as any)} className="border rounded-lg p-2 text-sm"><option value="high">迫切</option><option value="medium">重要</option><option value="low">一般</option></select><select value={taskStatus} onChange={e=>setTaskStatus(e.target.value as any)} className="border rounded-lg p-2 text-sm"><option value="todo">待辦</option><option value="in_progress">進行中</option><option value="completed">已完成</option><option value="delayed">已延遲</option></select></div><div className="grid grid-cols-2 gap-2"><input type="number" min="0.5" step="0.5" value={taskHours} onChange={e=>setTaskHours(Number(e.target.value))} placeholder="預估工時" className="border rounded-lg p-2 text-sm"/><input type="date" value={taskDeadline} onChange={e=>setTaskDeadline(e.target.value)} className="border rounded-lg p-2 text-sm"/></div><textarea value={taskNotes} onChange={e=>setTaskNotes(e.target.value)} placeholder="工作備註／執行說明" className="w-full border rounded-lg p-2 text-sm"/><div className="flex justify-end gap-2"><button type="button" onClick={()=>setShowTaskModal(false)} className="px-3 py-2 border rounded-lg text-sm">取消</button><button className="px-3 py-2 bg-[#385244] text-white rounded-lg text-sm">儲存</button></div></form></div>}
  </div>;
};
export default WorkView;
