export type AgentId =
  | 'manager' | 'work' | 'study' | 'schedule' | 'research' | 'brainstorm' | 'email' | 'finance' | 'social' | 'hr';
export type AgentStatus = 'active' | 'upcoming';
export type DataSourceType = 'user' | 'demo';
export type CreatedByType = 'user' | 'system';
export interface AgentInfo { id: AgentId; name: string; roleName: string; tagline: string; description: string; status: AgentStatus; avatarIcon: string; colorScheme: { bg: string; text: string; border: string; ring: string; gradient: string }; responsibilities: string[]; }
export type ActivityStepStatus = 'queued' | 'running' | 'completed' | 'warning';
export interface AgentActivityLog { id: string; timestamp: string; stepIndex: number; fromAgent: AgentId; toAgent?: AgentId; action: string; summary: string; detail?: string; status: ActivityStepStatus; durationMs?: number; }
export interface StructuredTimeBlock { time: string; type: 'work' | 'study' | 'rest' | 'buffer'; agentOwner: AgentId; title: string; duration: string; priority?: 'high' | 'medium' | 'low'; tips?: string; }
export interface MultiAgentResult { intentType: 'WORK' | 'STUDY' | 'HYBRID' | 'GENERAL' | 'MENTAL_TASK_INTAKE'; delegatedAgents: AgentId[]; activityLogs: AgentActivityLog[]; workAgentOutput?: { summary: string; highPriorityTasks: string[]; suggestedDurationHours: number; breakdown: string }; studyAgentOutput?: { summary: string; focusSubject: string; studyPlan: string; supervisionNote: string; suggestedDurationHours: number }; finalSynthesisMarkdown: string; proposedTimeBlocks?: StructuredTimeBlock[]; createdTaskPayload?: any; }
export interface ChatMessage { id: string; sender: 'user' | 'manager' | 'agent'; text: string; timestamp: string; agentId?: string; agentName?: string; agentRole?: string; intentType?: 'WORK' | 'STUDY' | 'HYBRID' | 'GENERAL' | 'MENTAL_TASK_INTAKE'; delegatedAgents?: AgentId[]; activityLogs?: AgentActivityLog[]; workOutput?: string; studyOutput?: string; proposedTimeBlocks?: StructuredTimeBlock[]; isThinking?: boolean; }
export interface WorkProject { id: string; workspaceId: string; title: string; category: string; progress: number; priority: 'high' | 'medium' | 'low'; deadline: string; description: string; status: 'planning' | 'in_progress' | 'completed' | 'on_hold'; owner?: string; tags: string[]; source: DataSourceType; createdBy?: CreatedByType; }
export interface WorkTask { id: string; workspaceId: string; projectId: string; projectName: string; title: string; priority: 'high' | 'medium' | 'low'; status: 'todo' | 'in_progress' | 'completed' | 'delayed'; startDate?: string; deadline: string; estimatedHours: number; assignee?: string; notes?: string; tags?: string[]; isUrgent?: boolean; source: DataSourceType; createdBy?: CreatedByType; }
export interface StudySubject { id: string; name: string; code: string; credits: number; progress: number; nextExamDate?: string; supervisorTone?: string; teacherOrNotes?: string; status: 'in_progress' | 'completed' | 'exam_prep'; focusTopics?: string[]; source: DataSourceType; }
export interface StudyTask { id: string; subjectId: string; subjectName: string; title: string; type: 'study_task' | 'assignment' | 'exam'; chapter?: string; deadline: string; progress: number; estimatedHours: number; priority: 'high' | 'medium' | 'low'; difficulty?: 'hard' | 'medium' | 'easy'; status: 'todo' | 'in_progress' | 'completed' | 'delayed'; supervisionNote?: string; notes?: string; source: DataSourceType; createdBy?: CreatedByType; }
export interface TodayTimeBlock { id: string; timeRange: string; type: 'work' | 'study' | 'rest' | 'buffer'; title: string; agentOwner: AgentId; targetDurationMin: number; completed: boolean; notes?: string; source: DataSourceType; createdBy?: CreatedByType; }
export interface Person { id: string; name: string; role?: string; email?: string; avatar?: string; source?: DataSourceType; createdBy?: CreatedByType; }
export interface DiscussionRecord { id: string; timestamp: string; title: string; topic?: string; summary: string; participants: string[]; actionItems?: string[]; source?: DataSourceType; createdBy?: CreatedByType; }
export interface InitialAppState { workProjects: WorkProject[]; workTasks: WorkTask[]; studySubjects: StudySubject[]; studyTasks: StudyTask[]; discussionRecords: DiscussionRecord[]; people: Person[]; todayBlocks: TodayTimeBlock[]; }
